services:
  rssfeed:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: rssfeed
    ports:
    - 9628:9628/tcp
    volumes:
    - .:/go/src/github.com/cixtor/rssfeed
version: '3.1'

